# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
#fastlane_version "2.18.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc ""
  lane :increment_build do 
    increment_build_number
    commit_version_bump
  end

  desc "Example: 3.1.1 to 3.1.2"
  lane :increment_version_patch do 
    increment_version_number(
      bump_type: "patch"
    )
    commit_version_bump
  end

  desc "Example: 3.1.1 to 3.2"
  lane :increment_version_minor do 
    increment_version_number(
      bump_type: "minor"
    )
    commit_version_bump
  end

  desc "Example: 3.1.1 to 4"
  lane :increment_version_major do 
    increment_version_number(
      bump_type: "major"
    )
    commit_version_bump
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "iFlynax",
      clean: true,
      skip_build: false,
      skip_slack: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    increment_build_number

    gym(
      scheme: "iFlynax",
      clean: true
    )

    pilot
    clean_build_artifacts

    commit_version_bump(
      message: 'Version Bump by fastlane',
      xcodeproj: 'iFlynax.xcodeproj',
      force: true
    )

    # sh "your_script.sh"
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # notify "Fastlane finished '#{lane}'" # Mac OS X Notification

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
